
ENABLE_SLIM : 0  # 改成1使build_config.yaml生效

MODULES:
  - ENABLE_AUDIO_CLASSIFICATION : 1
  - ENABLE_FACE_ATTRIBUTE : 0
  - ENABLE_FACE_DETECTION : 1
  - ENABLE_FACE_LANDMARK : 1
  - ENABLE_FEATURE_EXTRACT : 0
  - ENABLE_IMAGE_CLASSIFICATION : 0
  - ENABLE_KEYPOINTS_DETECTION : 1
  - ENABLE_LICENSE_PLATE_RECOGNITION : 1
  - ENABLE_OBJECT_DETECTION : 1
  - ENABLE_OBJECT_TRACKING : 0
  - ENABLE_SEGMENTATION : 0
  - ENABLE_SPEECH_RECOGNITION : 0  #会导致额外的库加入，不需要时可不启用
  - ENABLE_APP_PIPELINE : 0



#修改build_config.yaml后，需先clean_tdl_sdk再编译
#APP_PIPELINE的使用需保证OBJECT_DETECTION、FACE_DETECTION及FACE_LANDMARK为ENABLE状态

